<a href="https://colab.research.google.com/github/sngca09/DATA-SCIENCE-LAB/blob/main/Anakha_TA_CO2_Student_23_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aim: Program to implement k-NN classification using any standard dataset
available in the public domain and find the accuracy of the algorithm

Algorithm: 

The class of an unknown instance is computed using the following steps:

1. The distance between the unknown instance and all other training instances is computed.
2. The k nearest neighbors are identified.
3. The class labels of the k nearest neighbors are used to determine the class label of the unknown instance by using techniques like majority voting.

In [ ]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
iris=datasets.load_iris()
x,y=iris.data[:,:],iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,stratify=y,random_state=20,train_size=.8)


In [ ]:
# Identify the ideal value for k
score=[]
for k in range(1,15):
  knn=neighbors.KNeighborsClassifier(n_neighbors=k)
  knn.fit(x_train,y_train)
  y_pred=knn.predict(x_test)
  score.append(accuracy_score(y_test,y_pred))
  print("when k=%s, accu is %s"%(k,accuracy_score(y_test,y_pred)))



when k=1, accu is 0.9666666666666667
when k=2, accu is 0.9666666666666667
when k=3, accu is 0.9666666666666667
when k=4, accu is 0.9666666666666667
when k=5, accu is 0.9666666666666667
when k=6, accu is 0.9666666666666667
when k=7, accu is 0.9666666666666667
when k=8, accu is 0.9666666666666667
when k=9, accu is 0.9666666666666667
when k=10, accu is 0.9666666666666667
when k=11, accu is 1.0
when k=12, accu is 1.0
when k=13, accu is 1.0
when k=14, accu is 1.0


In [ ]:
from numpy.ma.extras import notmasked_contiguous
# S4.2: Train kNN regressor model for 'k = 6'.
knn6=neighbors.KNeighborsClassifier(n_neighbors=6)
knn6.fit(x_train,y_train)

# Perform prediction using 'predict()' function.

y_t_pre=knn6.predict(x_test)
# Call the 'score()' function to check the accuracy score of the train set and test set.
print("test set accuracy=",knn6.score(x_test,y_test))
print("confusion matrix")
print(confusion_matrix(y_test,y_t_pre))
print(classification_report(y_test,y_t_pre))

test set accuracy= 0.9666666666666667
confusion matrix
[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

