<a href="https://colab.research.google.com/github/sngca09/DATA-SCIENCE-LAB/blob/main/ANAKHA_TA_CO_1_Matrix_Operations_%26_Creating_a_dataframe_30_11_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Matrix Operations

#### Matrices

In [ ]:
# Create a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
import pandas as pd
m1=np.matrix('1 2 3;4 5 6')
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Convert a nested Python list into a matrix using the 'matrix()' function of the 'numpy' module.
m2=np.matrix([[1,2,3],[4,5,6]])
m2

matrix([[1, 2, 3],
        [4, 5, 6]])

#### Matrix Multiplication



$$\begin{bmatrix} 8 & 7 \\ 3	& -5	\\\end{bmatrix} \begin{bmatrix} 3 \\ 2 \\\end{bmatrix}$$

To multiply two matrices, you have to use the `matmul()` function of the `numpy` module. It takes two matrices to be multiplied as inputs and returns a new matrix.

In [ ]:
# Multiplication of the above two matrices.
m1=np.matrix('8 7 ; 3 -5')
m2=np.matrix('3;2')
mul=np.matmul(m1,m2)
mul

matrix([[38],
        [-1]])

**Note:** The number of columns in the first matrix should be the same as the number of rows in the second matrix. Otherwise, you will get `ValueError`

####  Identity Matrix

In [ ]:
# Create an identity matrix of the dimension 5 and of 'int' type.
im=np.identity(5,dtype=int)
im

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Now let's multiply a square matrix with an identity matrix of the same dimension (say 3).

In [ ]:
# Multiply a square matrix with an identity matrix of the same dimension.
ma=np.matrix('1 2 3;4 5 6;7 8 9')
inma=np.identity(3,dtype=int)
ans=np.matmul(ma,inma)
ans

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

----

####  Multiplicative Inverse of a Matrix^


Eg. let $A$ be a matrix of dimension $3$

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

Then its inverse is

$$A^{-1} = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix}$$

Both $A$ and $A^{-1}$ have the same dimension.

If you multiply the matrix $A$ with its inverse, you should get the identity matrix of dimension $3$.

$$A^{-1} A = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix} \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 7 \times 1 - 3 \times 1 -3 \times 1 &7 \times 3 - 3 \times 4 -3 \times 3 & 7 \times 3 - 3 \times 3 - 3 \times 4 \\ -1 \times 1 + 1 \times 1 + 0 \times 1 & -1 \times 3 + 1 \times 4 + 0 \times 3 & -1 \times 3 + 1 \times 3 + 0 \times 4 \\ -1 \times 1 + 0 \times 1 + 1 \times 1 & -1 \times 3 + 0 \times 4 + 1 \times 3 & -1 \times 3 + 0 \times 3 + 1 \times 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{bmatrix}$$


In [ ]:
#Multiply the above matrix with its inverse.
A=np.matrix('1 3 3;1 4 3;1 3 4')
inv=np.linalg.inv(A)
ans2=np.matmul(A,inv)
ans2

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### Determinant of a Matrix^^


$$X = \begin{bmatrix} 8 & 7 \\ 3	& -5 \\\end{bmatrix}$$

 To calculate the determinant value of a square matrix, use the `linalg.det()` function of the `numpy` module.

**Syntax:** `np.linalg.det(a)`

where `a` is some square matrix.

In [ ]:
# Calculate the determinant of the matrix X.
X=np.matrix('8 7;3 -5')
det=np.linalg.det(X)
det

-60.99999999999995

Let's calculate the determinant of the matrix

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

using Python.

In [ ]:
#Calculate the determinant of the above matrix A.
A1=np.matrix('1 3 3;1 4 3;1 3 4')
det1=np.linalg.det(A1)
det1

1.0

In [ ]:
# Calculate the inverse of the above matrix A.
inv2=np.linalg.inv(A1)
inv2

matrix([[ 7., -3., -3.],
        [-1.,  1.,  0.],
        [-1.,  0.,  1.]])

In [ ]:
#Create a dictionary to store weatherdata and convert it to a dtaframe
weather={'day':['19/06/202','3/5/21','4/6/21','8/09/2021','7/09/21','4/5/21'],
         'temp':[36,89,52,40,54,80],
         'place':['kochi','perumbavoor','kuruppampady','ekm','kolenchery','edappaly'],
         'windspeed':[67,90,30,10,15,67]}
dt=pd.DataFrame(weather)
# Display the first five rows of dataframe
dt.head()



day  temp         place  windspeed
0  19/06/202    36         kochi         67
1     3/5/21    89   perumbavoor         90
2     4/6/21    52  kuruppampady         30
3  8/09/2021    40           ekm         10
4    7/09/21    54    kolenchery         15

In [ ]:
#Display the last five rows of dataframe
dt.tail()


day  temp         place  windspeed
1     3/5/21    89   perumbavoor         90
2     4/6/21    52  kuruppampady         30
3  8/09/2021    40           ekm         10
4    7/09/21    54    kolenchery         15
5     4/5/21    80      edappaly         67